apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: synth-maus-local
  namespace: chemsynth
  labels:
    app: askcos
    app.kubernetes.io/part-of: askcos
spec:
  secretName: synth-maus-local-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - synth.maus.local
