apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: synth-maus-local-tls
  namespace: chemsynth
spec:
  secretName: synth-maus-local-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - synth.maus.local
