---  
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: askcos-ingress
  namespace: chemsynth
spec:
  rules:
  - host: synth.maus.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chemsynth
            port:
              name: websecure

  tls:
  - secretName: synth-maus-local-tls
