apiVersion: apps/v1
kind: Deployment
metadata:
  name: askcos-celery-worker
  namespace: chemsynth
  labels:
    app: askcos-celery
    app.kubernetes.io/part-of: askcos
    version: "2.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: askcos-celery
  template:
    metadata:
      labels:
        app: askcos-celery
        app.kubernetes.io/part-of: askcos
        version: "2.0"
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: celery
          image: registry.gitlab.com/mlpds_mit/askcosv2/askcos2_core/celery:2.0
          imagePullPolicy: IfNotPresent
          command:
            - celery
            - -A
            - askcos_site
            - worker
            - -c
            - "2"
            - -Q
            - atom_mapping_worker,cr_network_worker,descriptors_worker,sites_worker,tffp_worker,tb_coordinator_mcts,tb_c_worker
            - -n
            - celery_worker@%h
            - --pool=gevent
          envFrom:
            - configMapRef:
                name: askcos-config
            - secretRef:
                name: askcos-env
          env:
            - name: MONGO_PW
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: mongodb-password
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: mongodb-root-password
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: rabbitmq-password
          volumeMounts:
            - name: precompute-data
              mountPath: /ASKCOSv2/askcos2_core/data/precompute
            - name: buyables-cache
              mountPath: /ASKCOSv2/askcos2_core/data/db/buyables
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 8Gi
              cpu: 2
      volumes:
        - name: precompute-data
          persistentVolumeClaim:
            claimName: askcos-precompute-data
        - name: buyables-cache
          persistentVolumeClaim:
            claimName: askcos-buyables-cache
