apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: chemsynth
  labels:
    app: rabbitmq
    app.kubernetes.io/part-of: askcos
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      app.kubernetes.io/part-of: askcos
  template:
    metadata:
      labels:
        app: rabbitmq
        app.kubernetes.io/part-of: askcos
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.11-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: http
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: rabbitmq-username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: rabbitmq-password
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 500m
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
        labels:
          app: rabbitmq
          app.kubernetes.io/part-of: askcos
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: chemsynth
  labels:
    app: rabbitmq
    app.kubernetes.io/part-of: askcos
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      name: http
  selector:
    app: rabbitmq
    app.kubernetes.io/part-of: askcos
