apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: askcos-chemsynth
  namespace: argocd
  labels:
    app.kubernetes.io/name: askcos
    app.kubernetes.io/part-of: chemsynth
spec:
  project: default
  source:
    repoURL: https://github.com/stafel/ch.git
    targetRevision: main
    path: k8s/chemsynth
    directoryRecurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: chemsynth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data
